/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalhorobson;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author vanes
 */
public class TelaCadastro extends javax.swing.JFrame {
    
    private Clientes clientes;
    private MySQL conexao;

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
        clientes = new Clientes();
        conexao = new MySQL("localhost:3306", "bdclientesac2", "root", "01121965");
    }
    
    private void limparCamposBusca(){
        buscarNOME.setText("");
        buscarCPF.setText("");
        buscarTELEFONE.setText("");
        buscarCIDADE.setText("");
        buscarUF.setText("");
        buscarEMAIL.setText("");
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        inserirNOME = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inserirCPF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inserirTELEFONE = new javax.swing.JTextField();
        inserirCIDADE = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        inserirUF = new javax.swing.JTextField();
        BtnCADASTRAR = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        inserirEMAIL = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnBUSCAR = new javax.swing.JButton();
        btnLIMPAR = new javax.swing.JButton();
        buscarCIDADE = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        buscarUF = new javax.swing.JTextField();
        buscarCPF = new javax.swing.JTextField();
        btnATUALIZAR = new javax.swing.JButton();
        btnDELETAR = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        buscarNOME = new javax.swing.JTextField();
        buscarTELEFONE = new javax.swing.JTextField();
        buscarEMAIL = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 51));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/WhatsApp Image 2022-11-08 at 20.05.56.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setText("Nome");

        inserirNOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirNOMEActionPerformed(evt);
            }
        });

        jLabel3.setText("CPF");

        jLabel4.setText("Telefone");

        jLabel5.setText("Cidade");

        inserirCIDADE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirCIDADEActionPerformed(evt);
            }
        });

        jLabel6.setText("UF");

        BtnCADASTRAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastrar.jpeg"))); // NOI18N
        BtnCADASTRAR.setText("Cadastrar");
        BtnCADASTRAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCADASTRARMouseClicked(evt);
            }
        });
        BtnCADASTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCADASTRARActionPerformed(evt);
            }
        });

        jLabel7.setText("E-mail");

        jLabel8.setText("Cadastro Cliente");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(221, 221, 221)
                            .addComponent(BtnCADASTRAR))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(inserirCIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(inserirUF))
                                    .addComponent(inserirNOME)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inserirEMAIL))))
                    .addComponent(jLabel8)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inserirCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inserirTELEFONE, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inserirNOME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inserirCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inserirTELEFONE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inserirCIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(inserirUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(inserirEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnCADASTRAR)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel9.setText("Busca de Clientes");

        jLabel10.setText("CPF");

        jLabel11.setText("Cidade");

        btnBUSCAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/buscar.jpeg"))); // NOI18N
        btnBUSCAR.setText("Buscar");
        btnBUSCAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBUSCARMouseClicked(evt);
            }
        });

        btnLIMPAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Limpar.jpeg"))); // NOI18N
        btnLIMPAR.setText("Limpar");
        btnLIMPAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLIMPARMouseClicked(evt);
            }
        });

        buscarCIDADE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCIDADEActionPerformed(evt);
            }
        });

        jLabel12.setText("UF");

        btnATUALIZAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/atualizar.jpeg"))); // NOI18N
        btnATUALIZAR.setText("Atualizar");
        btnATUALIZAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnATUALIZARMouseClicked(evt);
            }
        });

        btnDELETAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lixo.jpeg"))); // NOI18N
        btnDELETAR.setText("Excluir");
        btnDELETAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDELETARMouseClicked(evt);
            }
        });

        jLabel13.setText("Nome");

        jLabel14.setText("Telefone");

        jLabel15.setText("E-mail");

        buscarEMAIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarEMAILActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarTELEFONE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(buscarEMAIL))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buscarCPF)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(btnBUSCAR)
                                        .addGap(57, 57, 57)
                                        .addComponent(btnLIMPAR))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(btnATUALIZAR)
                                        .addGap(99, 99, 99)
                                        .addComponent(btnDELETAR))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(buscarCIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buscarUF, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(2, 8, Short.MAX_VALUE))
                            .addComponent(buscarNOME))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel9)
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(buscarCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBUSCAR)
                    .addComponent(btnLIMPAR))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(buscarNOME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(buscarTELEFONE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(buscarEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarCIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(buscarUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDELETAR)
                    .addComponent(btnATUALIZAR))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inserirCIDADEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirCIDADEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inserirCIDADEActionPerformed

    private void inserirNOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirNOMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inserirNOMEActionPerformed

    private void buscarCIDADEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCIDADEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarCIDADEActionPerformed

    private void BtnCADASTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCADASTRARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCADASTRARActionPerformed

    private void buscarEMAILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarEMAILActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarEMAILActionPerformed

    private void BtnCADASTRARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCADASTRARMouseClicked
      // vou inserir um novo cliente aqui
      
        clientes.setNOME(inserirNOME.getText());
        clientes.setCPF(inserirCPF.getText());
        clientes.setTELEFONE(inserirTELEFONE.getText());
        clientes.setCIDADE(inserirCIDADE.getText());
        clientes.setUF(inserirUF.getText());
        clientes.setEMAIL(inserirEMAIL.getText());
        conexao.conectaBanco();
        String query;
        query = ("INSERT INTO clientes ("
                + "NOME,"
                + "CPF,"
                + "TELEFONE,"
                + "CIDADE,"
                + "UF,"
                + "EMAIL"
                + ") VALUES ("
                + "'" + clientes.getNOME() + "',"
                + "'" + clientes.getCPF() + "',"
                + "'" + clientes.getTELEFONE() + "',"
                + "'" + clientes.getCIDADE() + "',"
                + "'" + clientes.getUF() + "',"
                + "'" + clientes.getEMAIL() + "'"
                + ");");
        conexao.insertSQL(query);
        conexao.fechaBanco();
        
        
    }//GEN-LAST:event_BtnCADASTRARMouseClicked

    private void btnBUSCARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBUSCARMouseClicked
        // buscar CPF:
        
        
        conexao.conectaBanco();
        
        String buscarCPF = this.buscarCPF.getText();
        
        try {
          conexao.executarSQL(
                "SELECT "
                  + "NOME,"
                  + "TELEFONE,"
                  + "CIDADE,"
                  + "UF,"
                  + "EMAIL"
              + " FROM"
                  + " clientes"
              + " WHERE"
                  + " CPF = '" + buscarCPF + "'"
              + ";"      
        );
        
          while(conexao.getResultSet().next()){
                clientes.setNOME(conexao.getResultSet().getString(1));
                clientes.setTELEFONE(conexao.getResultSet().getString(2));
                clientes.setCIDADE(conexao.getResultSet().getString(3));
                clientes.setUF(conexao.getResultSet().getString(4));
                clientes.setEMAIL(conexao.getResultSet().getString(5));
          }
          
          
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
        
        buscarNOME.setText(clientes.getNOME());
        buscarTELEFONE.setText(clientes.getTELEFONE());
        buscarCIDADE.setText(clientes.getCIDADE());
        buscarUF.setText(clientes.getUF());
        buscarEMAIL.setText(clientes.getEMAIL());
        
        conexao.fechaBanco();
        }
        
        
        
    
    }//GEN-LAST:event_btnBUSCARMouseClicked

    private void btnLIMPARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLIMPARMouseClicked
        // Limpar campos de busca
       
        limparCamposBusca();
       
    }//GEN-LAST:event_btnLIMPARMouseClicked

    private void btnDELETARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDELETARMouseClicked
        // Deletar Dados
        
        conexao.conectaBanco();
        
        String buscarCPF = this.buscarCPF.getText();
        
        try {            
            conexao.updateSQL(
                "DELETE FROM clientes "
                + " WHERE "
                    + "CPF = '" + buscarCPF + "'"
                + ";"            
            );
            
        } finally{
            conexao.fechaBanco();
            limparCamposBusca();            
        }     
    }//GEN-LAST:event_btnDELETARMouseClicked

    private void btnATUALIZARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnATUALIZARMouseClicked
        // Atualizar Dados
        
        conexao.conectaBanco();
        
        String buscarCPF = this.buscarCPF.getText();
        
        try {
            conexao.updateSQL(
                "UPDATE clientes SET "
                   + "NOME = '" + buscarNOME.getText() + "',"
                   + "TELEFONE = '" + buscarTELEFONE.getText() + "',"
                   + "CIDADE = '" + buscarCIDADE.getText() + "',"
                   + "UF = '" + buscarUF.getText() + "',"
                   + "EMAIL = '" + buscarEMAIL.getText() + "'"
              + " WHERE "  
                   + "CPF = '" + buscarCPF + "'"
              + ";"
            
            );
            
        }finally{
           conexao.fechaBanco();
           limparCamposBusca(); 
            
        }

            
    }//GEN-LAST:event_btnATUALIZARMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCADASTRAR;
    private javax.swing.JButton btnATUALIZAR;
    private javax.swing.JButton btnBUSCAR;
    private javax.swing.JButton btnDELETAR;
    private javax.swing.JButton btnLIMPAR;
    private javax.swing.JTextField buscarCIDADE;
    private javax.swing.JTextField buscarCPF;
    private javax.swing.JTextField buscarEMAIL;
    private javax.swing.JTextField buscarNOME;
    private javax.swing.JTextField buscarTELEFONE;
    private javax.swing.JTextField buscarUF;
    private javax.swing.JTextField inserirCIDADE;
    private javax.swing.JTextField inserirCPF;
    private javax.swing.JTextField inserirEMAIL;
    private javax.swing.JTextField inserirNOME;
    private javax.swing.JTextField inserirTELEFONE;
    private javax.swing.JTextField inserirUF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

   
}
